=== DjobaDELATV/seygo_data/schema/v1/skill.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "title": "Skill",
  "description": "A Duel Links Skill (not a physical card).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json"
    },
    "id": {
      "description": "The UUID of this skill.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of languages to textual skill information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the skill.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the skill.",
            "type": "string"
          },
          "effect": {
            "description": "The effect text of the skill.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official?",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "Always 'skill-dl' for Duel Links skills.",
      "const": "skill-dl"
    },
    "skillType": {
      "description": "The type of skill (Legendary, Archive).",
      "type": "string"
    },
    "supports": {
      "description": "List of card names this skill supports or mentions.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "supportsArchetypes": {
      "description": "List of archetypes this skill supports.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releases": {
      "description": "How this skill can be obtained.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "character",
          "type"
        ],
        "properties": {
          "character": {
            "description": "The character associated with this release.",
            "type": "string"
          },
          "type": {
            "description": "The release type (duel_reward, level_up, trader, etc.).",
            "type": "string"
          },
          "details": {
            "description": "Additional details (e.g., 'Level 20').",
            "type": "string"
          }
        }
      }
    },
    "externalIDs": {
      "description": "IDs from external sources.",
      "type": "object",
      "properties": {
        "yugipedia": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "id": {
                "type": "integer"
              }
            }
          }
        }
      }
    }
  }
}

=== DjobaDELATV/seygo_data/skills/06f4350c-af4f-4a87-9be6-a112faf4a55e.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "06f4350c-af4f-4a87-9be6-a112faf4a55e",
  "text": {
    "en": {
      "name": "Burst Trigger",
      "effect": "1: At the beginning of your first turn, add 1 \"Polymerization\" from outside your Deck to your hand. During this Duel, you can only Fusion Summon \"Blue-Eyes\" Fusion Monsters."
    },
    "fr": {
      "name": "Amorce Explosive",
      "effect": "1 : Au d\u00e9but de votre premier tour, ajoutez 1 \"Polym\u00e9risation\" \u00e0 votre main depuis l'ext\u00e9rieur de votre Deck. Pendant ce Duel, vous ne pouvez Invoquer par Fusion que des Monstres Fusion \"Yeux Bleus\"."
    },
    "ja": {
      "name": ""
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Polymerization (Duel Links)",
    "Fusion Monster"
  ],
  "supportsArchetypes": [
    "Blue-Eyes"
  ],
  "releases": [
    {
      "character": "Seto Kaiba (Duel Links)",
      "type": "box",
      "details": "Character Deck (Kaiba Deck)"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Burst Trigger",
        "id": 1182982
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/69009247-bfcb-4a9a-ab7d-aa1bf46167b1.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "69009247-bfcb-4a9a-ab7d-aa1bf46167b1",
  "text": {
    "en": {
      "name": "Extra, Extra",
      "effect": "Can be used when your Life Points decrease by 2000. During your Draw Phase, add to your hand 1 copy of the card you drew as your normal draw.\nThis Skill can only be used once per Duel."
    },
    "fr": {
      "name": "Encore, encore",
      "effect": "Comp\u00e9tence qui peut \u00eatre utilis\u00e9e quand vos Life Points diminuent de 2 000. En Draw Phase, ajoutez \u00e0 votre main 1 exemplaire de la carte re\u00e7ue en pioche normale.\nCette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": "\u5897\u5237",
      "effect": "\u81ea\u5206\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff12\uff10\uff10\uff10\u6e1b\u3063\u305f\u5f8c\u3001\u81ea\u5206\u306e\u30c9\u30ed\u30fc\u30d5\u30a7\u30a4\u30ba\u306e\u30c9\u30ed\u30fc\u524d\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u901a\u5e38\u306e\u30c9\u30ed\u30fc\u3067\u5f15\u3044\u305f\u30ab\u30fc\u30c9\uff11\u679a\u3092\uff12\u679a\u306b\u8907\u88fd\u3059\u308b\u3002\n\u3053\u306e\u30b9\u30ad\u30eb\u306f\u30c7\u30e5\u30a8\u30eb\u4e2d\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "releases": [
    {
      "character": "Maximillion Pegasus (Duel Links)",
      "type": "duel_reward"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Extra, Extra",
        "id": 714902
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/3cd4a379-c3e6-4691-bf55-28eed5d0916c.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "3cd4a379-c3e6-4691-bf55-28eed5d0916c",
  "text": {
    "en": {
      "name": "Plant's Exchange",
      "effect": "This Skill can be used twice per Duel.1: During your Main Phase, place 1 Level 5 or higher Plant Type monster from your hand to the bottom of your Deck, and then draw 1 card."
    },
    "fr": {
      "name": "Transaction Plante",
      "effect": "Cette Comp\u00e9tence peut \u00eatre utilis\u00e9e deux fois par Duel.1 : Au d\u00e9but de votre Main Phase, placez 1 monstre de Type Plante de Niveau 5 ou plus de votre main au-dessous de votre Deck, puis piochez 1 carte."
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Plant"
  ],
  "releases": [
    {
      "character": "Akiza Izinski (Duel Links)",
      "type": "trader"
    },
    {
      "character": "Luna (Duel Links)",
      "type": "trader"
    },
    {
      "character": "Yuri (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Spectre (Duel Links)",
      "type": "trader"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Plant's Exchange",
        "id": 1101599
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/13e2ce22-3f33-4c10-9330-c23260ea5d78.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "13e2ce22-3f33-4c10-9330-c23260ea5d78",
  "text": {
    "en": {
      "name": "Bear Parade",
      "effect": "Each of the following effects can be used once per turn and once per Duel by selecting 1 \"Frightfur Bear\" you control.\n* Select 1 monster in your opponent's Graveyard and equip it to this card as an Equip Card. The card equipped counts as having been equipped by the effect of this \"Frightfur Bear\".\n* During this turn, the selected monster gains an additional attack for each card it has equipped."
    },
    "fr": {
      "name": "Parade de l'ours",
      "effect": "Chacun des effets suivants peut \u00eatre utilis\u00e9 une fois par tour et une fois par Duel en s\u00e9lectionnant 1 \"Ours Frourreur\" que vous contr\u00f4lez.\n* S\u00e9lectionnez 1 monstre dans le Cimeti\u00e8re de votre adversaire et \u00e9quipez-le \u00e0 cette carte en tant que Carte d'\u00c9quipement. La carte \u00e9quip\u00e9e compte comme ayant \u00e9t\u00e9 \u00e9quip\u00e9e par l'effet de cette Carte \"Ours Frourreur\".\n* Lors de ce tour, le monstre s\u00e9lectionn\u00e9 gagne une attaque suppl\u00e9mentaire pour chaque carte qu'il a \u00e9quip\u00e9e."
    },
    "ja": {
      "name": ""
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Frightfur Bear (Duel Links)"
  ],
  "releases": [
    {
      "character": "Sora Perse (Duel Links)",
      "type": "level_up",
      "details": "Level 20"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Bear Parade",
        "id": 713584
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/7a7dbe2c-f459-498a-8841-6f26afaf5713.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "7a7dbe2c-f459-498a-8841-6f26afaf5713",
  "text": {
    "en": {
      "name": "Deck Master: \"Kaiser Sea Horse\"",
      "effect": "You can only use this Skill's first and second effects once per Duel.1: During your Main Phase, play 1 \"Kaiser Sea Horse\" from outside your Deck in face-down Defense Position. (Its battle position can be changed.)2: If you control \"Kaiser Sea Horse\", you can Normal Summon a LIGHT monster with 1 less Tribute this turn."
    },
    "fr": {
      "name": ""
    },
    "ja": {
      "name": ""
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Kaiser Sea Horse (Duel Links)",
    "LIGHT"
  ],
  "releases": [
    {
      "character": "Seto Kaiba (Duel Links)",
      "type": "mission",
      "details": "Style mission reward"
    },
    {
      "character": "Seto Kaiba (Duel Links)",
      "type": "mission",
      "details": "Win 5 Duel(s) with \"Kaiser Sea Horse\" in your Deck, while playing as Seto Kaiba (Urban)."
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Deck Master: \"Kaiser Sea Horse\"",
        "id": 1151867
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/1c23679a-b236-4daf-8a04-dc7301bfe997.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "1c23679a-b236-4daf-8a04-dc7301bfe997",
  "text": {
    "en": {
      "name": "Extra Pain",
      "effect": "When you deal battle damage to your opponent, deal an additional 100 damage.\nThis Skill will not activate if your opponent has 1000 Life Points or less."
    },
    "fr": {
      "name": "Douleur suppl\u00e9mentaire",
      "effect": "Lorsque vous infligez des dommages de combat \u00e0 votre adversaire, infligez 100 dommages suppl\u00e9mentaires.\nCette Comp\u00e9tence ne s'active pas si votre adversaire a 1 000 Life Points ou moins."
    },
    "ja": {
      "name": "\u4eca\u56de\u306e\u30c6\u30fc\u30de\u306f\u2026\u2026\u300c\u75db\u307f\u300d\u3060\u3041\uff01\uff01",
      "effect": "\u76f8\u624b\u306b\u6226\u95d8\u30c0\u30e1\u30fc\u30b8\u3092\u4e0e\u3048\u305f\u5834\u5408\u3001\u3055\u3089\u306b\u76f8\u624b\u306b\uff15\uff10\u30dd\u30a4\u30f3\u30c8\u306e\u75db\u307f\u3092\u4e0e\u3048\u308b\u3002\u3053\u306e\u30b9\u30ad\u30eb\u306f\u76f8\u624b\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff11\uff10\uff10\uff10\u4ee5\u4e0b\u306e\u5834\u5408\u9069\u7528\u3055\u308c\u306a\u3044\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "releases": [
    {
      "character": "Scud (Duel Links)",
      "type": "level_up",
      "details": "Level 13"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Extra Pain",
        "id": 714899
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/54d0c823-454a-4855-82ba-c2152cb1d42e.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "54d0c823-454a-4855-82ba-c2152cb1d42e",
  "text": {
    "en": {
      "name": "Destiny Board (Skill)",
      "effect": "Can be used if \"Dark Necrofear\" is in your Graveyard, and your Life Points are at 2000 or below.\nAt the end of your fifth turn after activating this Skill, you win the Duel.\nThis Skill is negated if \"Dark Necrofear\" leaves your Graveyard.\nThis Skill can only be used once per Duel."
    },
    "fr": {
      "name": "Tableau de la Destin\u00e9e",
      "effect": "Comp\u00e9tence qui peut \u00eatre utilis\u00e9e si \"Necrofear des T\u00e9n\u00e8bres\" est dans votre Cimeti\u00e8re et si vos Life Points sont \u00e0 2 000 ou moins.\n\u00c0 la fin de votre cinqui\u00e8me tour apr\u00e8s l'activation de cette Comp\u00e9tence, vous gagnez le Duel.\nCette Comp\u00e9tence est annul\u00e9e si \"Necrofear des T\u00e9n\u00e8bres\" quitte votre Cimeti\u00e8re.\nCette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": "\u30a6\u30a3\u30b8\u30e3\u76e4",
      "effect": "\u81ea\u5206\u306e\u5893\u5730\u306b\u300c\u30c0\u30fc\u30af\u30fb\u30cd\u30af\u30ed\u30d5\u30a3\u30a2\u300d\u304c\u5b58\u5728\u3057\u3001\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff12\uff10\uff10\uff10\u4ee5\u4e0b\u306e\u5834\u5408\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\n\u30b9\u30ad\u30eb\u4f7f\u7528\u5f8c\uff15\u56de\u76ee\u306e\u81ea\u5206\u306e\u30bf\u30fc\u30f3\u7d42\u4e86\u6642\u306b\u30c7\u30e5\u30a8\u30eb\u306b\u52dd\u5229\u3059\u308b\u3002\n\u300c\u30c0\u30fc\u30af\u30fb\u30cd\u30af\u30ed\u30d5\u30a3\u30a2\u300d\u304c\u81ea\u5206\u306e\u5893\u5730\u304b\u3089\u96e2\u308c\u305f\u3068\u304d\u3001\u3053\u306e\u30b9\u30ad\u30eb\u306f\u7121\u52b9\u306b\u306a\u308b\u3002\n\u3053\u306e\u30b9\u30ad\u30eb\u306f\u30c7\u30e5\u30a8\u30eb\u4e2d\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Dark Necrofear (Duel Links)"
  ],
  "releases": [
    {
      "character": "Yami Bakura (Duel Links)",
      "type": "duel_reward"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Destiny Board (Skill)",
        "id": 714521
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/92fea460-0a43-4063-859c-3d7f2bda70be.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "92fea460-0a43-4063-859c-3d7f2bda70be",
  "text": {
    "en": {
      "name": "Barian Battlemorph! Sargasso, the Dark Realm",
      "effect": "You can only use this Skill's second effect once per turn.\n1: At the beginning of the Duel, place 1 \"Sargasso the D.D. Battlefield\" from outside of your Deck face-up in your Field Zone. During this Duel, you can only Normal or Special Summon \"Star Seraph\" monsters (excluding Special Summons from the Extra Deck).\n2: Shuffle 1 card from your hand into the Deck and reveal 1 \"Sargasso Lighthouse\" or \"Sargasso the D.D. Battlefield\" in your hand. Barian Battlemorph! Regain your true form! Add 1 \"Star Seraph\" monster from your Deck to your hand and play 1 \"Star Seraph Sage\" from outside of your Deck to your field in face-down Defense Position. (Its battle position can be changed.)"
    },
    "fr": {
      "name": "Transformation de combat Barian ! Sargasso, le Royaume des T\u00e9n\u00e8bres",
      "effect": "Vous pouvez utiliser le deuxi\u00e8me effet de cette Comp\u00e9tence une fois par tour.\n1 : Au d\u00e9but du Duel, placez 1 \"Champ de Bataille D.D. de Sargasso\" dans votre Zone Terrain face recto depuis l'ext\u00e9rieur de votre Deck. Pendant ce Duel, vous pouvez uniquement Invoquer Normalement ou Sp\u00e9cialement des monstres \"S\u00e9raphin \u00c9toile\" (hors Invocations Sp\u00e9ciales depuis l'Extra Deck).\n2 : M\u00e9langez 1 carte de votre main dans le Deck et r\u00e9v\u00e9lez 1 \"Phare de Sargasso\" ou \"Champ de Bataille D.D. de Sargasso\" dans votre main. Transformation de combat Barian ! Retrouve ta forme v\u00e9ritable ! Ajoutez 1 monstre \"S\u00e9raphin \u00c9toile\" depuis votre Deck \u00e0 votre main et jouez 1 \"Sage S\u00e9raphin \u00c9toile\" depuis l'ext\u00e9rieur de votre Deck sur votre Terrain en Position de D\u00e9fense face verso. (Sa position de combat peut \u00eatre modifi\u00e9e.)"
    },
    "ja": {
      "name": "\u30d0\u30ea\u30a2\u30eb\u30d5\u30a9\u30fc\u30bc \uff0d\u9b54\u5883\u30b5\u30eb\u30ac\u30c3\u30bd\uff0d",
      "effect": "\u3053\u306e\u30b9\u30ad\u30eb\u306e\u2461\u306e\u52b9\u679c\u306f\uff11\u30bf\u30fc\u30f3\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002\n\u2460\uff1a\u30c7\u30e5\u30a8\u30eb\u958b\u59cb\u6642\u306b\u767a\u52d5\u3059\u308b\u3002\u30c7\u30c3\u30ad\u5916\u304b\u3089\u300c\u7570\u6b21\u5143\u306e\u53e4\u6226\u5834\uff0d\u30b5\u30eb\u30ac\u30c3\u30bd\u300d\uff11\u679a\u3092\u81ea\u5206\u306e\u30d5\u30a3\u30fc\u30eb\u30c9\u30be\u30fc\u30f3\u306b\u8868\u5074\u8868\u793a\u3067\u7f6e\u304f\u3002\u3053\u306e\u30c7\u30e5\u30a8\u30eb\u4e2d\u3001\u81ea\u5206\u306f\u300c\u5149\u5929\u4f7f\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\u3057\u304b\u53ec\u559a\u30fb\u7279\u6b8a\u53ec\u559a\u3067\u304d\u306a\u3044\uff08\uff25\uff38\u30c7\u30c3\u30ad\u304b\u3089\u306e\u7279\u6b8a\u53ec\u559a\u3092\u9664\u304f\uff09\u3002\n\u2461\uff1a\u624b\u672d\u3092\uff11\u679a\u30c7\u30c3\u30ad\u306b\u623b\u3057\u3001\u624b\u672d\u306e\u300c\u30b5\u30eb\u30ac\u30c3\u30bd\u306e\u706f\u53f0\u300d\u304b\u300c\u7570\u6b21\u5143\u306e\u53e4\u6226\u5834\uff0d\u30b5\u30eb\u30ac\u30c3\u30bd\u300d\uff11\u679a\u3092\u76f8\u624b\u306b\u898b\u305b\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u30d0\u30ea\u30a2\u30eb\u30d5\u30a9\u30fc\u30bc\u3057\u3001\u771f\u306e\u59ff\u306b\u306a\u308b\uff01\n\u30c7\u30c3\u30ad\u304b\u3089\u300c\u5149\u5929\u4f7f\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\u624b\u672d\u306b\u52a0\u3048\u3001\u30c7\u30c3\u30ad\u5916\u304b\u3089\u300c\u5149\u5929\u4f7f\u30d6\u30c3\u30af\u30b9\u300d\uff11\u4f53\u3092\u88cf\u5074\u5b88\u5099\u8868\u793a\u3067\u51fa\u3059\uff08\u8868\u793a\u5f62\u5f0f\u5909\u66f4\u53ef\u80fd\uff09\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Sargasso the D.D. Battlefield (Duel Links)",
    "Sargasso Lighthouse (Duel Links)",
    "Star Seraph Sage (Duel Links)"
  ],
  "supportsArchetypes": [
    "Star Seraph"
  ],
  "releases": [
    {
      "character": "Dumon (Duel Links)",
      "type": "duel_reward"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Barian Battlemorph! Sargasso, the Dark Realm",
        "id": 1075310
      }
    ]
  }
}
